tunnel: bce7e259-b454-412c-b65a-a50f4e3a9f4c
credentials-file: C:\Users\wouter.bon\mtls-server\credentials.json
protocol: http2

ingress:
  - hostname: mtls.nietst.uk
    service: tcp://127.0.0.1:9445
  - hostname: nietst.uk
    service: tcp://127.0.0.1:9445
  - service: http_status:404
